[build.environment]
  # Permite que VITE_API_URL se compile en el cÃ³digo
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL"

[build]
  command = "rm -rf .cache node_modules/.vite attached_assets dist 2>/dev/null; npm install && npm run build"
  publish = "dist/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
